### ISSUE TITLE
Hyperbolicity

### ISSUE THREAD

**Issue by daidaren202** [HazyResearch/hgcn#24]
Hi, Thanks for your great work. I got a problem while calculating 'Hyperbolicity' of Cora. The value you reported is  $\delta$ = 11. 
However, I use the code you released (./utils/hyperbolicity.py) to calculate the 'Hyperbolicity' of Cora. I got $\delta$ = 2.5. I am confused and did i do something wrong?

Thanks.

**Comment by duskybomb** [comment]
Hi @daidaren202, I used the code to calculate the hyperbolicity for a custom graph dataset. Once, I got <img src="https://render.githubusercontent.com/render/math?math=\gamma = 6">  and the other time i got <img src="https://render.githubusercontent.com/render/math?math=\gamma = 1.5">.

I think this is because of:
https://github.com/HazyResearch/hgcn/blob/a526385744da25fc880f3da346e17d0fe33817f8/utils/hyperbolicity.py#L18

As you can see, they are taking two nodes at random and calculating the hyperbolicity if a path exists between the nodes. 
Finally, the function returns the maximum hyperbolicity that they calculated.

I am not sure if this was of any help. But I guess you might now know why you are getting a different result to that reported in the paper.

**Comment by daidaren202** [comment]
Hi, @duskybomb. Thanks for your reminder. I have noticed that the original code randomly samples 4 points to calculate the hyperbolicity, and repeats 50,000 (default) times, reporting the maximum value. 

To avoid inaccurate hyperbolicity caused by too few sampling times (50,000), I set the number of repetitions to 10,000,000. Run twice, I got the same \delta=3.0. 

There are 2708 points in Cora. For a 4-point sampling without putting back, there are 2708 x 2707 x 2706 x 2705 \approx 5 x10^13 different permutations.  Is it necessary to set the number of repetitions to such a large amount? I am trying to set a larger number than 10,000,000, but it is too time-consuming. 

How do you think? Look forward to your reply. Thanks.
