### ISSUE TITLE
Why do you consider the positive validation edges and positive test edges as negative training edges?

### ISSUE THREAD

**Issue by Abigale001** [HazyResearch/hgcn#25]
`val_edges, test_edges, train_edges = pos_edges[:n_val], pos_edges[n_val:n_test + n_val], pos_edges[n_test + n_val:]`
    `val_edges_false, test_edges_false = neg_edges[:n_val], neg_edges[n_val:n_test + n_val]`
  ` train_edges_false = np.concatenate([neg_edges, val_edges, test_edges], axis=0)`

As shown the code in the above `mask_edges` function, why do you consider the positive validation edges and positive test edges as the negative training edges? I think it may misunderstand the model training.

**Comment by ines-chami** [comment]
During training, the validation and test edges are unobserved and the goal in link prediction is to recover those missing links. Therefore, the model only has access to training links and all the other links (validation and test) are treated as negatives.

**Comment by ruilialice** [comment]
In the training process, all positive validation edges and positive test edges are treated as the negative training edges, but in the validation and testing process, these edges are treated as positive edges. I am confused about this. According to your assumption, "the model only has access to training links and all the other links (validation and test) are treated as negatives",  maybe when computing the training loss, we could only consider the neg_edges as train_edges_false and ignore the positive validation edges and positive test edges, instead of considering (neg_edges, positive validation edges and  positive test edges) as the train_edges_false?
