### ISSUE TITLE
Raise OOM error when train 15000 items

### ISSUE THREAD

**Issue by Abigale001** [HazyResearch/hgcn#26]
I use hnn and delete most of the train_neg (only ten times of train_pos) to train link prediction task. But my GPU is out of memory. How to solve it?

**Comment by ines-chami** [comment]
You can try reducing the batch size if the current one does not fit into your GPU memory.

**Comment by Abigale001** [comment]
But it feeds the adj matrix in the model and doesn't have batch size parameter.

**Comment by AdarshMJ** [comment]
Hi! @ines-chami I have a similar problem. Unable to run  the link prediction task on the PubMed dataset. I'm using google colab for training and it stops because of tcmalloc: large alloc 3109773312 error. How to set the batch size? Any insights are welcome.
@Abigale001 did you figure out the batching?

Thanks in advance!
